#!/usr/bin/python
def add_calc(number1, number2):
    answer = number1 + number2
    return answer
print(add_calc(5,70))
print(add_calc(5,7))
print(add_calc(8,74))
added_number = add_calc(5,5)
print(added_number + 20)
